import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link";
import { Mic, LayoutDashboard, BarChart3 } from "lucide-react";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-slate-950 text-slate-100 selection:bg-blue-500/30">
        <header className="sticky top-0 z-50 bg-slate-950/80 backdrop-blur-md border-b border-slate-800">
            <div className="max-w-5xl mx-auto px-4 h-14 flex items-center justify-between">
                <div className="font-bold text-lg tracking-tight bg-gradient-to-r from-blue-400 to-indigo-500 bg-clip-text text-transparent">
                    Tel-Setu
                </div>
                <nav className="flex gap-4">
                    <Link href="/" className="flex items-center gap-1.5 text-sm font-medium text-slate-400 hover:text-white transition-colors">
                        <Mic className="w-4 h-4" /> Capture
                    </Link>
                    <Link href="/planner" className="flex items-center gap-1.5 text-sm font-medium text-slate-400 hover:text-white transition-colors">
                        <LayoutDashboard className="w-4 h-4" /> Planner
                    </Link>
                    <Link href="/analytics" className="flex items-center gap-1.5 text-sm font-medium text-slate-400 hover:text-white transition-colors">
                        <BarChart3 className="w-4 h-4" /> Analytics
                    </Link>
                </nav>
            </div>
        </header>
        {children}
      </body>
    </html>
  );
}
